# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_value', models.FloatField()),
                ('lng_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coordinates',
            name='id_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Guest'),
        ),
    ]
